import {
	IBuyers,
	IOrder,
	IRecentOrders,
	IVendors,
	ITransactionHistory,
	IProducts,
	IOrederDetails,
	IBuyerOrder,
} from "@/interfaces/tables.interface";
import { images } from "@/constants/images";
import { IReview } from "@/interfaces/IReview";
import { IBestSellingProduct } from "@/interfaces/IBestSellingProduct";

export const vendorDetails = [
	{
		numbers: 978,
		text: "Total Vendors",
		bgImg: images.cardBg1,
		bg_gradient: "linear-gradient(180deg, #FCFDFF 0%, #FCFDFF 100%)",
		normalStyles: "top-2 right-0 bottom-0 w-[10rem]",
	},
	{
		numbers: 1278,
		text: "Total Listed Products",
		bgImg: images.cardBg2,
		bg_gradient: "linear-gradient(180deg, #FEFBFF 0%, #FEFBFF 100%)",
		normalStyles: "top-2 right-1 w-[9rem]",
	},
];
export const buyers_details = [
	{
		numbers: 94878,
		text: "Total Users",
		bgImg: images.cardImg1,
		bg_gradient: "linear-gradient(180deg, #FCFDFF 0%, #FCFDFF 100%)",
		normalStyles: "top-2 right-0 bottom-0 w-[10rem]",
	},
	{
		numbers: 42244,
		text: "Active Users",
		bgImg: images.cardBg2,
		bg_gradient: "linear-gradient(180deg, #FEFBFF 0%, #FEFBFF 100%)",
		normalStyles: "top-2 right-1 w-[9rem]",
	},
	{
		numbers: 21278,
		text: "Inactive Users",
		bgImg: images.cardImg3,
		bg_gradient: "linear-gradient(180deg, #FEFBFF 0%, #FEFBFF 100%)",
		normalStyles: "top-2 right-0 w-[10rem]",
	},
];

export const pie_data = [
	{ name: "Fashion", value: 400 },
	{ name: "Computer wares", value: 128 },
	{ name: "Books", value: 310 },
	{ name: "Toys", value: 200 },
	{ name: "Mobile Phones", value: 320 },
	{ name: "Arts & Crafts", value: 70 },
];
export const COLORS = [
	"#0088FE",
	"#00C49F",
	"#FFBB28",
	"#FF8042",
	"#C08AFE",
	"#2ECBAAE",
];
export const line_data = [
	{
		name: "Jan",
		revenue: 4000,
		order: 2400,
	},
	{
		name: "Feb",
		revenue: 3000,
		order: 1398,
	},
	{
		name: "Mar",
		revenue: 2000,
		order: 800,
	},
	{
		name: "Apr",
		revenue: 780,
		order: 1400,
	},
	{
		name: "May",
		revenue: 1890,
		order: 800,
	},
	{
		name: "Jun",
		revenue: 2390,
		order: 1240,
	},
	{
		name: "Jul",
		revenue: 3490,
		order: 2700,
	},
	{
		name: "Aug",
		revenue: 2181,
		order: 2500,
	},
	{
		name: "Sep",
		revenue: 3908,
		order: 2000,
	},
	{
		name: "Oct",
		revenue: 2290,
		order: 2210,
	},
	{
		name: "Nov",
		revenue: 3490,
		order: 2400,
	},
	{
		name: "Dec",
		revenue: 3490,
		order: 4300,
	},
];

export const db_product_data = [
	{
		id: 1,
		product: images.product1,
		product_name: "Shoes",
		price: 988,
		sold: 1088,
	},
	{
		id: 2,
		product: images.product,
		product_name: "Ghostbusters",
		price: 1984,
		sold: 2000,
	},
];
export const buyers_data: IBuyers[] = [
	{
		created_at: "1 Oct | 11:23am",
		email: "jobs@future.io",
		id: 1,
		phone: "33949234",
		profile_img: images.userImg,
		status: "active",
		username: "Steve Jobs",
	},
	{
		created_at: "1 Oct | 11:23am",
		email: "jobs@future.io",
		id: 2,
		phone: "33949234",
		profile_img: images.userImg,
		status: "active",
		username: "Steve Jobs",
	},
	{
		created_at: "1 Oct | 11:23am",
		email: "jobs@future.io",
		id: 3,
		phone: "33949234",
		profile_img: images.userImg,
		status: "active",
		username: "Steve Jobs",
	},
	{
		created_at: "1 Oct | 11:23am",
		email: "jobs@future.io",
		id: 4,
		phone: "33949234",
		profile_img: images.userImg,
		status: "active",
		username: "Steve Jobs",
	},
	{
		created_at: "1 Oct | 11:23am",
		email: "jobs@future.io",
		id: 5,
		phone: "33949234",
		profile_img: images.userImg,
		status: "active",
		username: "Steve Jobs",
	},
	{
		created_at: "1 Oct | 11:23am",
		email: "jobs@future.io",
		id: 6,
		phone: "33949234",
		profile_img: images.userImg,
		status: "active",
		username: "Steve Jobs",
	},
	{
		created_at: "1 Oct | 11:23am",
		email: "jobs@future.io",
		id: 7,
		phone: "33949234",
		profile_img: images.userImg,
		status: "active",
		username: "Steve Jobs",
	},
	{
		created_at: "1 Oct | 11:23am",
		email: "jobs@future.io",
		id: 8,
		phone: "33949234",
		profile_img: images.userImg,
		status: "active",
		username: "Steve Jobs",
	},
	{
		created_at: "1 Oct | 11:23am",
		email: "jobs@future.io",
		id: 9,
		phone: "33949234",
		profile_img: images.userImg,
		status: "active",
		username: "Steve Jobs",
	},
	{
		created_at: "1 Oct | 11:23am",
		email: "jobs@future.io",
		id: 10,
		phone: "33949234",
		profile_img: images.userImg,
		status: "active",
		username: "Steve Jobs",
	},
];

export const db_product_cols = [
	{
		name: "Product",
		selector: (row: { product_name: string }) => row.product_name,
		sortable: false,
	},
	{
		name: "Price",
		selector: (row: { price: string }) => row.price,
		sortable: true,
	},
	{
		name: "Sold",
		selector: (row: { sold: string }) => row.sold,
		sortable: true,
	},
];

export const vendors: IVendors[] = [
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Hereith Gospel",
	},
	{
		balance: 498431,
		created_at: "1 Oct | 11:23am",
		email: "ma@cot.io",
		itm_stock: 394,
		phone: "2253977204",
		status: "active",
		vendor_name: "Makinzel Cotton",
	},
	{
		balance: 273945,
		created_at: "1 Oct | 11:23am",
		email: "paeet@info.com",
		itm_stock: 298471,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Schemitz Carrot",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "sun1@hotmail.com",
		itm_stock: 1048,
		phone: "88948376244",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "fivemen@info.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Donna Kingston",
	},
	{
		balance: 109703,
		created_at: "1 Oct | 11:23am",
		email: "jama@wok.com",
		itm_stock: 7524,
		phone: "39394882924",
		status: "inactive",
		vendor_name: "Martha Jax",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Hereith Gospel",
	},
	{
		balance: 498431,
		created_at: "1 Oct | 11:23am",
		email: "ma@cot.io",
		itm_stock: 394,
		phone: "2253977204",
		status: "active",
		vendor_name: "Makinzel Cotton",
	},
	{
		balance: 273945,
		created_at: "1 Oct | 11:23am",
		email: "paeet@info.com",
		itm_stock: 298471,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Schemitz Carrot",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "sun1@hotmail.com",
		itm_stock: 1048,
		phone: "88948376244",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "fivemen@info.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Donna Kingston",
	},
	{
		balance: 109703,
		created_at: "1 Oct | 11:23am",
		email: "jama@wok.com",
		itm_stock: 7524,
		phone: "39394882924",
		status: "inactive",
		vendor_name: "Martha Jax",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Hereith Gospel",
	},
	{
		balance: 498431,
		created_at: "1 Oct | 11:23am",
		email: "ma@cot.io",
		itm_stock: 394,
		phone: "2253977204",
		status: "active",
		vendor_name: "Makinzel Cotton",
	},
	{
		balance: 273945,
		created_at: "1 Oct | 11:23am",
		email: "paeet@info.com",
		itm_stock: 298471,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Schemitz Carrot",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "sun1@hotmail.com",
		itm_stock: 1048,
		phone: "88948376244",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "fivemen@info.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Donna Kingston",
	},
	{
		balance: 109703,
		created_at: "1 Oct | 11:23am",
		email: "jama@wok.com",
		itm_stock: 7524,
		phone: "39394882924",
		status: "inactive",
		vendor_name: "Martha Jax",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Hereith Gospel",
	},
	{
		balance: 498431,
		created_at: "1 Oct | 11:23am",
		email: "ma@cot.io",
		itm_stock: 394,
		phone: "2253977204",
		status: "active",
		vendor_name: "Makinzel Cotton",
	},
	{
		balance: 273945,
		created_at: "1 Oct | 11:23am",
		email: "paeet@info.com",
		itm_stock: 298471,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Schemitz Carrot",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "sun1@hotmail.com",
		itm_stock: 1048,
		phone: "88948376244",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "fivemen@info.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Donna Kingston",
	},
	{
		balance: 109703,
		created_at: "1 Oct | 11:23am",
		email: "jama@wok.com",
		itm_stock: 7524,
		phone: "39394882924",
		status: "inactive",
		vendor_name: "Martha Jax",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Daniel Krone",
	},
	{
		balance: 47203,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 18524,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Jobs Pen",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "hzdkv@example.com",
		itm_stock: 100,
		phone: "07123456789",
		status: "active",
		vendor_name: "Hereith Gospel",
	},
	{
		balance: 498431,
		created_at: "1 Oct | 11:23am",
		email: "ma@cot.io",
		itm_stock: 394,
		phone: "2253977204",
		status: "active",
		vendor_name: "Makinzel Cotton",
	},
	{
		balance: 273945,
		created_at: "1 Oct | 11:23am",
		email: "paeet@info.com",
		itm_stock: 298471,
		phone: "04040483839",
		status: "inactive",
		vendor_name: "Schemitz Carrot",
	},
	{
		balance: 2293923,
		created_at: "1 Oct | 11:23am",
		email: "sun1@hotmail.com",
		itm_stock: 1048,
		phone: "88948376244",
		status: "active",
		vendor_name: "Mark Smith",
	},
	{
		balance: 1293923,
		created_at: "1 Oct | 11:23am",
		email: "fivemen@info.com",
		itm_stock: 3020,
		phone: "03049483839",
		status: "active",
		vendor_name: "Donna Kingston",
	},
	{
		balance: 109703,
		created_at: "1 Oct | 11:23am",
		email: "jama@wok.com",
		itm_stock: 7524,
		phone: "39394882924",
		status: "inactive",
		vendor_name: "Martha Jax",
	},
];
export const recent_order: IRecentOrders[] = [
	{
		id: 24,
		qty: 20,
		amount: 505,
		image: images.product,
		itm_name: "Product 1",
		order_date: "01 Oct | 11:22am",
		status: "Pending",
	},
	{
		id: 25,
		qty: 26,
		amount: 87,
		image: images.product6,
		itm_name: "Product 2",
		order_date: "01 Oct | 11:22am",
		status: "Paid",
	},
	{
		id: 26,
		qty: 85,
		amount: 318,
		image: images.product4,
		itm_name: "Product 3",
		order_date: "01 Oct | 11:22am",
		status: "Pending",
	},
	{
		id: 27,
		qty: 55,
		amount: 220,
		image: images.product5,
		itm_name: "Product 4",
		order_date: "01 Oct | 11:22am",
		status: "Cancelled",
	},
	{
		id: 27,
		qty: 55,
		amount: 220,
		image: images.product2,
		itm_name: "Product 5",
		order_date: "01 Oct | 11:22am",
		status: "Shipped",
	},
];

export const transactionHistory_data: ITransactionHistory[] = [
	{
		id: 1,
		event: "Credited",
		summary: "Afruna pay has credited you ",
		date: "1 Oct 2016",
		amount: `${"2000"}`,
		action: "$300",
	},
	{
		id: 2,
		event: "Credited",
		summary: "Afruna pay has credited you ",
		date: "1 Oct 2016",
		amount: `${"2000"}`,
		action: "$300",
	},
	{
		id: 3,
		event: "Credited",
		summary: "Afruna pay has credited you ",
		date: "1 Oct 2016",
		amount: `${"2000"}`,
		action: "$300",
	},
	{
		id: 4,
		event: "Credited",
		summary: "Afruna pay has credited you ",
		date: "1 Oct 2016",
		amount: `${"2000"}`,
		action: "$300",
	},
	{
		id: 5,
		event: "Withdrawal",
		summary: "Afruna pay has credited you ",
		date: "1 Oct 2016",
		amount: `${"2000"}`,
		action: "$300",
	},
	{
		id: 6,
		event: "Credited",
		summary: "Afruna pay has credited you ",
		date: "1 Feb 2016",
		amount: `${"2000"}`,
		action: "$300",
	},
	{
		id: 7,
		event: "Withdrawal",
		summary: "Afruna pay has credited you ",
		date: "1 May 2016",
		amount: `${"2000"}`,
		action: "$300",
	},
	{
		id: 8,
		event: "Credited",
		summary: "Afruna pay has credited you ",
		date: "1 Mar 2016",
		amount: `${"2000"}`,
		action: "$300",
	},
	{
		id: 9,
		event: "Listing fee",
		summary: "Afruna pay has credited you ",
		date: "1 Mar 2016",
		amount: `${"2000"}`,
		action: "$300",
	},
	{
		id: 10,
		event: "Credited",
		summary: "Afruna pay has credited you ",
		date: "1 Nov 2016",
		amount: `${"2000"}`,
		action: "$300",
	},
];

export const NewNotification = [
	{
		message: "You have 8 messages that needs your attention now",
		time: "47 min ago",
		check: false,
	},
	{
		message: "You have already view this message, continue",
		time: "1hr ago",
		check: true,
	},
];

export const oldNotification = [
	{
		message: "This message was read yesterday night when rain was falling",
		time: "2 days ago",
		check: true,
	},
	{
		message: "I want to place an Order two T-sheet and shoes ",
		time: "1 Day ago",
		check: true,
	},
];

export const reviewsRating = [
	{
		id: 1,
		name: "Majida umma Bhai",
		message:
			"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do tempor incididunt ut labore et dolore magna enim ad minim veniam, quis nostrud eiusmod  aliqua. Ut exercitation",
		date: "23/06/2023",
	},
	{
		id: 2,
		name: "Majida umma Bahai",
		message:
			"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do tempor incididunt ut labore et dolore magna enim ad minim veniam, quis nostrud eiusmod  aliqua. Ut exercitation",
		date: "23/06/2023",
	},
	{
		id: 3,
		name: "Majida umma Bahai",
		message:
			"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do tempor incididunt ut labore et dolore magna enim ad minim veniam, quis nostrud eiusmod  aliqua. Ut exercitation",
		date: "23/06/2023",
	},
	{
		id: 4,
		name: "Majida umma Bahai",
		message:
			"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do tempor incididunt ut labore et dolore magna enim ad minim veniam, quis nostrud eiusmod  aliqua. Ut exercitation",
		date: "23/06/2023",
	},
	{
		id: 5,
		name: "Majida umma Bahai",
		message:
			"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do tempor incididunt ut labore et dolore magna enim ad minim veniam, quis nostrud eiusmod  aliqua. Ut exercitation",
		date: "23/06/2023",
	},
	{
		id: 6,
		name: "Majida umma Bahai",
		message:
			"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do tempor incididunt ut labore et dolore magna enim ad minim veniam, quis nostrud eiusmod  aliqua. Ut exercitation",
		date: "23/06/2023",
	},
	{
		id: 7,
		name: "Majida umma Bahai",
		message:
			"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do tempor incididunt ut labore et dolore magna enim ad minim veniam, quis nostrud eiusmod  aliqua. Ut exercitation",
		date: "23/06/2023",
	},
	{
		id: 8,
		name: "Majida umma Bahai",
		message:
			"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do tempor incididunt ut labore et dolore magna enim ad minim veniam, quis nostrud eiusmod  aliqua. Ut exercitation",
		date: "23/06/2023",
	},
];
export const users = [
	{
		id: 1,
		img: images.userImg,
		name: "Bhai jan ADMIN",
		number: 4,
		active: true,
	},
	{
		id: 2,
		img: images.userImg1,
		name: "Bhai jan ADMIN",
		number: 2,
		active: true,
	},
	{
		id: 3,
		img: images.profileImg,
		name: "Bhai jan ADMIN",
		number: 1,
		active: true,
	},
	{
		id: 4,
		img: images.userImg,
		name: "Bhai jan ADMIN",
		number: 0,
		active: false,
	},
	{
		id: 5,
		img: images.userImg,
		name: "Bhai jan ADMIN",
		number: 0,
		active: false,
	},
	{
		id: 6,
		img: images.userImg1,
		name: "Bhai jan ADMIN",
		number: 0,
		active: false,
	},
	{
		id: 7,
		img: images.profileImg,
		name: "Bhai jan ADMIN",
		number: 0,
		active: true,
	},
	{
		id: 8,
		img: images.userImg,
		name: "Bhai jan ADMIN",
		number: 0,
		active: true,
	},
	{
		id: 9,
		img: images.userImg1,
		name: "Bhai jan ADMIN",
		number: 0,
		active: true,
	},
	{
		id: 5,
		img: images.userImg,
		name: "Bhai jan ADMIN",
		number: 0,
		active: false,
	},
	{
		id: 6,
		img: images.userImg1,
		name: "Bhai jan ADMIN",
		number: 0,
		active: false,
	},
	{
		id: 7,
		img: images.profileImg,
		name: "Bhai jan ADMIN",
		number: 0,
		active: true,
	},
	{
		id: 8,
		img: images.userImg,
		name: "Bhai jan ADMIN",
		number: 0,
		active: true,
	},
	{
		id: 9,
		img: images.userImg1,
		name: "Bhai jan ADMIN",
		number: 0,
		active: true,
	},
	{
		id: 5,
		img: images.userImg,
		name: "Bhai jan ADMIN",
		number: 0,
		active: false,
	},
	{
		id: 6,
		img: images.userImg1,
		name: "Bhai jan ADMIN",
		number: 0,
		active: false,
	},
	{
		id: 7,
		img: images.profileImg,
		name: "Bhai jan ADMIN",
		number: 0,
		active: true,
	},
	{
		id: 8,
		img: images.userImg,
		name: "Bhai jan ADMIN",
		number: 0,
		active: true,
	},
	{
		id: 9,
		img: images.userImg1,
		name: "Bhai jan ADMIN",
		number: 0,
		active: true,
	},
	{
		id: 5,
		img: images.userImg,
		name: "Bhai jan ADMIN",
		number: 0,
		active: false,
	},
	{
		id: 6,
		img: images.userImg1,
		name: "Bhai jan ADMIN",
		number: 0,
		active: false,
	},
	{
		id: 7,
		img: images.profileImg,
		name: "Bhai jan ADMIN",
		number: 0,
		active: true,
	},
	{
		id: 8,
		img: images.userImg,
		name: "Bhai jan ADMIN",
		number: 0,
		active: true,
	},
	{
		id: 9,
		img: images.userImg1,
		name: "Bhai jan ADMIN",
		number: 0,
		active: true,
	},
	{
		id: 5,
		img: images.userImg,
		name: "Bhai jan ADMIN",
		number: 0,
		active: false,
	},
	{
		id: 6,
		img: images.userImg1,
		name: "Bhai jan ADMIN",
		number: 0,
		active: false,
	},
	{
		id: 7,
		img: images.profileImg,
		name: "Bhai jan ADMIN",
		number: 0,
		active: true,
	},
	{
		id: 8,
		img: images.userImg,
		name: "Bhai jan ADMIN",
		number: 0,
		active: true,
	},
	{
		id: 9,
		img: images.userImg1,
		name: "Bhai jan ADMIN",
		number: 0,
		active: true,
	},
	{
		id: 5,
		img: images.userImg,
		name: "Bhai jan ADMIN",
		number: 0,
		active: false,
	},
	{
		id: 6,
		img: images.userImg1,
		name: "Bhai jan ADMIN",
		number: 0,
		active: false,
	},
	{
		id: 7,
		img: images.profileImg,
		name: "Bhai jan ADMIN",
		number: 0,
		active: true,
	},
	{
		id: 8,
		img: images.userImg,
		name: "Bhai jan ADMIN",
		number: 0,
		active: true,
	},
	{
		id: 9,
		img: images.userImg1,
		name: "Bhai jan ADMIN",
		number: 0,
		active: true,
	},
];

export const conversations = [
	{
		id: 1,
		img: images.userImg1,
		message: "Hi Jov Dov",
		time: "8:00 PM",
		isOwn: false,
	},
	{
		id: 2,
		img: images.userImg,
		message: "What sup",
		time: "8:00 PM",
		isOwn: true,
	},
	{
		id: 3,
		img: images.userImg,
		message: "Lorem ipsum hassince the 257678suusdh",
		time: "8:00 PM",
		isOwn: false,
	},
	{
		id: 4,
		img: images.userImg,
		message: "Lorem ipsum hasipsum has been  been the industry ",
		time: "8:00 PM",
		isOwn: true,
	},
	{
		id: 5,
		img: images.userImg1,
		message: "Lorem ipsum has been the industry",
		time: "8:00 PM",
		isOwn: false,
	},
	{
		id: 6,
		img: images.userImg1,
		message:
			"Lorem ipsum has been the industry standard dummy psum standard dummy text ever since",
		time: "8:00 PM",
		isOwn: false,
	},
	{
		id: 7,
		img: images.userImg,
		message:
			"Lorem ipsum has been the industry standard dummy text ever standard dummy text ever",
		time: "8:00 PM",
		isOwn: true,
	},
	{
		id: 8,
		img: images.userImg,
		message: "Lorem ipsum has ever standard dummy text ever",
		time: "8:00 PM",
		isOwn: true,
	},
	{
		id: 9,
		img: images.userImg1,
		message:
			"Lorem ipsum has been the industry standard dummy text ever standard dummy text ever",
		time: "8:00 PM",
		isOwn: false,
	},
	{
		id: 10,
		img: images.userImg,
		message:
			"Lorem ipsum  dummy text ever standard has been the industry standard dummy text ever standard dummy text ever",
		time: "8:00 PM",
		isOwn: true,
	},
	{
		id: 11,
		img: images.userImg1,
		message: "Lorem ipsum ever standard dummy text ever",
		time: "8:00 PM",
		isOwn: false,
	},
	{
		id: 12,
		img: images.userImg,
		message: "Lorem ipsum ever standard dummy text ever",
		time: "8:00 PM",
		isOwn: true,
	},
	{
		id: 13,
		img: images.userImg1,
		message: "Lorem ipsum ever standard dummy text ever",
		time: "8:00 PM",
		isOwn: false,
	},
	{
		id: 14,
		img: images.userImg,
		message: "Lorem ipsum ever standard dummy text ever",
		time: "8:00 PM",
		isOwn: true,
	},
	{
		id: 15,
		img: images.userImg1,
		message: "Lorem ipsum ever standard dummy text ever",
		time: "8:00 PM",
		isOwn: false,
	},
	{
		id: 16,
		img: images.userImg,
		message: "Lorem ipsum ever standard dummy text ever",
		time: "8:00 PM",
		isOwn: true,
	},
	{
		id: 17,
		img: images.userImg1,
		message: "Lorem ipsum ever standard dummy text ever",
		time: "8:00 PM",
		isOwn: false,
	},
	{
		id: 18,
		img: images.userImg,
		message: "Lorem ipsum ever standard dummy text ever",
		time: "8:00 PM",
		isOwn: true,
	},
	{
		id: 19,
		img: images.userImg1,
		message: "Lorem ipsum ever standard dummy text ever",
		time: "8:00 PM",
		isOwn: false,
	},
	{
		id: 20,
		img: images.userImg,
		message: "Lorem ipsum ever standard dummy text ever",
		time: "8:00 PM",
		isOwn: true,
	},
];

export const products: IBestSellingProduct[] = [
	{
		id: 738,
		image: images.product,
		name: "Kartik Cloth",
		price: 337,
		status: "instock",
		stock: 362,
		total_sales: 101,
	},
	{
		id: 838,
		image: images.product7,
		name: "Kartik Cloth",
		price: 337,
		status: "instock",
		stock: 362,
		total_sales: 101,
	},
	{
		id: 1030,
		image: images.product5,
		name: "Kartik Cloth",
		price: 337,
		status: "out-of-stock",
		stock: 362,
		total_sales: 101,
	},
	{
		id: 2893,
		image: images.product2,
		name: "Kartik Cloth",
		price: 337,
		status: "out-of-stock",
		stock: 362,
		total_sales: 101,
	},
	{
		id: 2970,
		image: images.product4,
		name: "Kartik Cloth",
		price: 337,
		status: "instock",
		stock: 362,
		total_sales: 101,
	},
];

export const reviews: IReview[] = [
	{
		comment: "The product came well packaged and I loved it.",
		date: new Date(),
		img: images.profileImg,
		name: "James Toshima",
		rated: 5,
	},
	{
		comment: "The product came well packaged and I loved it.",
		date: new Date(),
		img: images.profileImg,
		name: "Juan Toshima",
		rated: 3,
	},
	{
		comment: "The product came well packaged and I loved it.",
		date: new Date(),
		img: images.profileImg,
		name: "Jane Toshima",
		rated: 5,
	},
	{
		comment: "The product came well packaged and I loved it.",
		date: new Date(),
		img: images.profileImg,
		name: "Jolly Toshima",
		rated: 4,
	},
];

export const orderCardDetails = [
	{
		numbers: "356,70k",
		text: "New Orders",
		bgImg: images.cardBg1,
		bg_gradient: "linear-gradient(180deg, #CDDFFD 0%, #FCFDFF 100%)",
		OrderStyles: "top-4 right-0",
	},
	{
		numbers: "45k",
		text: "Pending Orders",
		bgImg: images.cardBg2,
		bg_gradient: "linear-gradient(180deg, #FCF2DA 0%, #FCFDFF 100%)",
		OrderStyles: "top-0 right-0",
	},
	{
		numbers: "1578,40k",
		text: "Delivered Orders",
		bgImg: images.cardBg2,
		bg_gradient: "linear-gradient(180deg, #CDF7EC 0%, #FCFDFF 100%)",
		OrderStyles: "top-0 right-0",
	},
	{
		numbers: "10k",
		text: "Canceled Orders",
		bgImg: images.cardBg2,
		bg_gradient: "linear-gradient(180deg, #FCDAE2 0%, #FCFDFF 100%)",
		OrderStyles: "top-0 right-0",
	},
];

export const orderData: IOrder[] = [
	{
		id: 6545,
		buyers_name: "Leo Paula Jaboati",
		img: images.product1,
		item_name: "Hand craft footwearee",
		amount: 237,
		order_date: "01 Oct,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Cash on Delivery",
		delivery_status: "Shipped",
	},
	{
		id: 2964,
		buyers_name: "Steve Jobs",
		img: images.product1,
		item_name: "craft footwear",
		amount: 457,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Master Card",
		delivery_status: "Delivered",
	},
	{
		id: 2545,
		buyers_name: "Steve Jov Don",
		img: images.product1,
		item_name: "T-Shirt",
		amount: 457,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Verve Card",
		delivery_status: "Pickup",
	},
	{
		id: 8545,
		buyers_name: "Jov Don",
		img: images.product1,
		item_name: "Two piars of shoes",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Visa",
		delivery_status: "Pending",
	},
	{
		id: 1545,
		buyers_name: "Drisy Don",
		img: images.product1,
		item_name: "Two piars of shoes",
		amount: 1000,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Master Card",
		delivery_status: "Canceled",
	},
	{
		id: 7545,
		buyers_name: "Jov Don",
		img: images.product1,
		item_name: "Back bag",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Cash on Delivery",
		delivery_status: "Returnedvered",
	},
	{
		id: 8545,
		buyers_name: "Jov Don",
		img: images.product1,
		item_name: "Two piars of shoes",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Visa",
		delivery_status: "Pending",
	},
	{
		id: 1545,
		buyers_name: "Drisy Don",
		img: images.product1,
		item_name: "Two piars of shoes",
		amount: 1000,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Master Card",
		delivery_status: "Canceled",
	},
	{
		id: 7545,
		buyers_name: "Jov Don",
		img: images.product1,
		item_name: "Back bag",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Cash on Delivery",
		delivery_status: "Returnedvered",
	},
	{
		id: 3945,
		buyers_name: "Suleiman SYD",
		img: images.product1,
		item_name: "Back bag",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Visa",
		delivery_status: "Delivered",
	},
	{
		id: 6545,
		buyers_name: "Leo Paula Jaboati",
		img: images.product1,
		item_name: "Hand craft footwearee",
		amount: 237,
		order_date: "01 Oct,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Cash on Delivery",
		delivery_status: "Shipped",
	},
	{
		id: 2964,
		buyers_name: "Steve Jobs",
		img: images.product1,
		item_name: "craft footwear",
		amount: 457,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Master Card",
		delivery_status: "Delivered",
	},
	{
		id: 2545,
		buyers_name: "Steve Jov Don",
		img: images.product1,
		item_name: "T-Shirt",
		amount: 457,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Verve Card",
		delivery_status: "Pickup",
	},
	{
		id: 8545,
		buyers_name: "Jov Don",
		img: images.product1,
		item_name: "Two piars of shoes",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Visa",
		delivery_status: "Pending",
	},
	{
		id: 1545,
		buyers_name: "Drisy Don",
		img: images.product1,
		item_name: "Two piars of shoes",
		amount: 1000,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Master Card",
		delivery_status: "Canceled",
	},
	{
		id: 7545,
		buyers_name: "Jov Don",
		img: images.product1,
		item_name: "Back bag",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Cash on Delivery",
		delivery_status: "Returnedvered",
	},
	{
		id: 8545,
		buyers_name: "Jov Don",
		img: images.product1,
		item_name: "Two piars of shoes",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Visa",
		delivery_status: "Pending",
	},
	{
		id: 1545,
		buyers_name: "Drisy Don",
		img: images.product1,
		item_name: "Two piars of shoes",
		amount: 1000,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Master Card",
		delivery_status: "Canceled",
	},
	{
		id: 7545,
		buyers_name: "Jov Don",
		img: images.product1,
		item_name: "Back bag",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Cash on Delivery",
		delivery_status: "Returnedvered",
	},
	{
		id: 8545,
		buyers_name: "Jov Don",
		img: images.product1,
		item_name: "Two piars of shoes",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Visa",
		delivery_status: "Pending",
	},
	{
		id: 1545,
		buyers_name: "Drisy Don",
		img: images.product1,
		item_name: "Two piars of shoes",
		amount: 1000,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Master Card",
		delivery_status: "Canceled",
	},
	{
		id: 7545,
		buyers_name: "Jov Don",
		img: images.product1,
		item_name: "Back bag",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Cash on Delivery",
		delivery_status: "Returnedvered",
	},
	{
		id: 3945,
		buyers_name: "Suleiman SYD",
		img: images.product1,
		item_name: "Back bag",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Visa",
		delivery_status: "Delivered",
	},
	{
		id: 6545,
		buyers_name: "Leo Paula Jaboati",
		img: images.product1,
		item_name: "Hand craft footwearee",
		amount: 237,
		order_date: "01 Oct,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Cash on Delivery",
		delivery_status: "Shipped",
	},
	{
		id: 2964,
		buyers_name: "Steve Jobs",
		img: images.product1,
		item_name: "craft footwear",
		amount: 457,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Master Card",
		delivery_status: "Delivered",
	},
	{
		id: 2545,
		buyers_name: "Steve Jov Don",
		img: images.product1,
		item_name: "T-Shirt",
		amount: 457,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Verve Card",
		delivery_status: "Pickup",
	},
	{
		id: 8545,
		buyers_name: "Jov Don",
		img: images.product1,
		item_name: "Two piars of shoes",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Visa",
		delivery_status: "Pending",
	},
	{
		id: 1545,
		buyers_name: "Drisy Don",
		img: images.product1,
		item_name: "Two piars of shoes",
		amount: 1000,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Master Card",
		delivery_status: "Canceled",
	},
	{
		id: 7545,
		buyers_name: "Jov Don",
		img: images.product1,
		item_name: "Back bag",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Cash on Delivery",
		delivery_status: "Returnedvered",
	},
	{
		id: 3945,
		buyers_name: "Suleiman SYD",
		img: images.product1,
		item_name: "Back bag",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Visa",
		delivery_status: "Delivered",
	},
	{
		id: 2964,
		buyers_name: "Steve Jobs",
		img: images.product1,
		item_name: "craft footwear",
		amount: 457,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Master Card",
		delivery_status: "Delivered",
	},
	{
		id: 2545,
		buyers_name: "Steve Jov Don",
		img: images.product1,
		item_name: "T-Shirt",
		amount: 457,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Verve Card",
		delivery_status: "Pickup",
	},
	{
		id: 8545,
		buyers_name: "Jov Don",
		img: images.product1,
		item_name: "Two piars of shoes",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Visa",
		delivery_status: "Pending",
	},
	{
		id: 1545,
		buyers_name: "Drisy Don",
		img: images.product1,
		item_name: "Two piars of shoes",
		amount: 1000,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Master Card",
		delivery_status: "Canceled",
	},
	{
		id: 7545,
		buyers_name: "Jov Don",
		img: images.product1,
		item_name: "Back bag",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Cash on Delivery",
		delivery_status: "Returnedvered",
	},
	{
		id: 3945,
		buyers_name: "Suleiman SYD",
		img: images.product1,
		item_name: "Back bag",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Visa",
		delivery_status: "Delivered",
	},
	{
		id: 2964,
		buyers_name: "Steve Jobs",
		img: images.product1,
		item_name: "craft footwear",
		amount: 457,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Master Card",
		delivery_status: "Delivered",
	},
	{
		id: 2545,
		buyers_name: "Steve Jov Don",
		img: images.product1,
		item_name: "T-Shirt",
		amount: 457,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Verve Card",
		delivery_status: "Pickup",
	},
	{
		id: 8545,
		buyers_name: "Jov Don",
		img: images.product1,
		item_name: "Two piars of shoes",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Visa",
		delivery_status: "Pending",
	},
	{
		id: 1545,
		buyers_name: "Drisy Don",
		img: images.product1,
		item_name: "Two piars of shoes",
		amount: 1000,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Master Card",
		delivery_status: "Canceled",
	},
	{
		id: 7545,
		buyers_name: "Jov Don",
		img: images.product1,
		item_name: "Back bag",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Cash on Delivery",
		delivery_status: "Returnedvered",
	},
	{
		id: 3945,
		buyers_name: "Suleiman SYD",
		img: images.product1,
		item_name: "Back bag",
		amount: 897,
		order_date: "01 Jan,2023",
		delivery_date: "07 Oct, 2023",
		method_of_payment: "Visa",
		delivery_status: "Delivered",
	},
];

export const OrederDetailsData: IOrederDetails[] = [
	{
		id: 6545,
		img: images.product1,
		itemName: "Pair of shoes",
		quantity: 4,
		orderDate: "2 Jan 2024",
		amount: 574,
	},
	{
		id: 4784,
		img: images.product2,
		itemName: "School bage",
		quantity: 2,
		orderDate: "24 Jan 2024",
		amount: 258,
	},
];
export const orderStatus = [
	{
		status: "Order Proccessing",
		date: "Tue, 30 Jan 2022",
		order_status: true,
	},
	{
		status: "Order Package",
		date: "Tue, 04 Jan 2022",
		order_status: true,
	},
	{
		status: "Order Shipped",
		date: "Thur, 04 Jan 2022",
		order_status: true,
	},
	{
		status: "Out for Delivery",
		date: "Thur, 04 Jan 2022",
		order_status: false,
	},
	{
		status: "Delivered",
		date: "Fri, 04 Feb 2022",
		order_status: false,
	},
];

export const categoryData = [
	{
		title: "Fashion",
		items: [
			"Casual Wears",
			"Formal Wears",
			"Blouse",
			"Abayas",
			"Skirt",
			"Casual Wears",
		],
		img: images.catgryFashn,
	},
	{
		title: "Arts & Craft",
		items: ["Hand Made item", "Panting", "Craft"],
		img: images.catgryCrafting,
	},
	{
		title: "Afruna movies",
		items: ["Action", "Comedy", "Drama", "History"],
		img: images.catgryMovie,
	},
	{
		title: "Books",
		items: ["History", "Science Flc", "Mange", "Horror"],
		img: images.catgryBook,
	},
	{
		title: "Computer Acesories",
		items: ["History", "Science Flc", "Mange"],
		img: images.catgryAcesory,
	},
	{
		title: "Computer Accessories",
		items: ["History", "Science Flc", "Mange", "Mange"],
		img: images.catgryAcesory,
	},
];

export const ProuctsData: IProducts[] = [
	{
		id: 1,
		productName: "Lativari dress",
		productImg: images.product1,
		category: "Fashion",
		stock: 37,
		rating: "4.5",
		price: 4000,
		order: 12,
		dateListed: "1 Oct | 11:23am",
	},
	{
		id: 2,
		productName: "School bag",
		productImg: images.product1,
		category: "Art & Craft",
		stock: 10,
		rating: "2.5",
		price: 2000,
		order: 27,
		dateListed: "2 Jan | 11:23am",
	},
	{
		id: 3,
		productName: "Round Neck",
		productImg: images.product1,
		category: "Computer Accessory",
		stock: 10,
		rating: "5",
		price: 2000,
		order: 27,
		dateListed: "2 Jan | 11:23am",
	},
	{
		id: 4,
		productName: "Shoes",
		productImg: images.product1,
		category: "Art & Craft",
		stock: 10,
		rating: "4.5",
		price: 2000,
		order: 27,
		dateListed: "2 Jan | 11:23am",
	},
	{
		id: 5,
		productName: "T-shirt",
		productImg: images.product1,
		category: "Afruna Movies",
		stock: 10,
		rating: "4.5",
		price: 2000,
		order: 27,
		dateListed: "2 Jan | 11:23am",
	},
	{
		id: 6,
		productName: "Round Neck",
		productImg: images.product1,
		category: "Fashion",
		stock: 10,
		rating: "3.5",
		price: 2000,
		order: 27,
		dateListed: "2 Jan | 11:23am",
	},
	{
		id: 7,
		productName: "School bag",
		productImg: images.product1,
		category: "Art & Craft",
		stock: 10,
		rating: "5",
		price: 2000,
		order: 27,
		dateListed: "2 Jan | 11:23am",
	},
	{
		id: 8,
		productName: "T-shirt",
		productImg: images.product1,
		category: "Art & Craft",
		stock: 10,
		rating: "3.5",
		price: 2000,
		order: 27,
		dateListed: "2 Jan | 11:23am",
	},
	{
		id: 9,
		productName: "T-shirt",
		productImg: images.product1,
		category: "Art & Craft",
		stock: 10,
		rating: "4.5",
		price: 2000,
		order: 27,
		dateListed: "2 Jan | 11:23am",
	},
	{
		id: 10,
		productName: "T-shirt",
		productImg: images.product1,
		category: "fashion",
		stock: 10,
		rating: "5",
		price: 2000,
		order: 27,
		dateListed: "2 Jan | 11:23am",
	},
	{
		id: 11,
		productName: "T-shirt",
		productImg: images.product1,
		category: "fashion",
		stock: 10,
		rating: "2.5",
		price: 2000,
		order: 27,
		dateListed: "2 Jan | 11:23am",
	},
	{
		id: 12,
		productName: "T-shirt",
		productImg: images.product1,
		category: "fashion",
		stock: 10,
		rating: "5",
		price: 2000,
		order: 27,
		dateListed: "2 Jan | 11:23am",
	},
	{
		id: 13,
		productName: "T-shirt",
		productImg: images.product1,
		category: "fashion",
		stock: 10,
		rating: "5",
		price: 2000,
		order: 27,
		dateListed: "2 Jan | 11:23am",
	},
	{
		id: 14,
		productName: "T-shirt",
		productImg: images.product1,
		category: "fashion",
		stock: 10,
		rating: "5",
		price: 2000,
		order: 27,
		dateListed: "2 Jan | 11:23am",
	},
	{
		id: 15,
		productName: "T-shirt",
		productImg: images.product1,
		category: "fashion",
		stock: 10,
		rating: "5",
		price: 2000,
		order: 27,
		dateListed: "2 Jan | 11:23am",
	},
	{
		id: 16,
		productName: "T-shirt",
		productImg: images.product1,
		category: "fashion",
		stock: 10,
		rating: "5",
		price: 2000,
		order: 27,
		dateListed: "2 Jan | 11:23am",
	},
	{
		id: 17,
		productName: "T-shirt",
		productImg: images.product1,
		category: "fashion",
		stock: 10,
		rating: "5",
		price: 2000,
		order: 27,
		dateListed: "2 Jan | 11:23am",
	},
];

export const BuyerOrderData: IBuyerOrder[] = [
	{
		id: 6745,
		img: images.product1,
		itemName: "Pair of shoes",
		quantity: 4,
		orderDate: "02 Jan | 11:29am",
		status: "paid",
		amount: 574,
	},
	{
		id: 8645,
		img: images.product,
		itemName: "Two piars of shoes",
		amount: 897,
		quantity: 2,
		orderDate: "02 Jan | 11:29am",
		status: "Pending",
	},
	{
		id: 2645,
		img: images.product3,
		itemName: "School bags",
		amount: 897,
		quantity: 3,
		orderDate: "02 Jan | 11:29am",
		status: "Canceled",
	},
	{
		id: 1545,
		img: images.product,
		itemName: "Three piars of shoes",
		amount: 897,
		quantity: 1,
		orderDate: "02 Jan | 11:29am",
		status: "Pending",
	},
	{
		id: 2545,
		img: images.product2,
		itemName: "T-Shirt",
		amount: 897,
		quantity: 2,
		orderDate: "02 Jan | 11:29am",
		status: "Paid",
	},
	{
		id: 3545,
		img: images.product5,
		itemName: "Two piars of shoes",
		amount: 397,
		quantity: 1,
		orderDate: "02 Jan | 11:29am",
		status: "Canceled",
	},
	{
		id: 4545,
		img: images.product2,
		itemName: "Two piars of shoes",
		amount: 897,
		quantity: 2,
		orderDate: "02 Jan | 11:29am",
		status: "Pending",
	},
	{
		id: 5545,
		img: images.product,
		itemName: "Two piars of shoes",
		amount: 497,
		quantity: 3,
		orderDate: "02 Jan | 11:29am",
		status: "Canceled",
	},
	{
		id: 6545,
		img: images.product1,
		itemName: "Two piars of shoes",
		amount: 897,
		quantity: 4,
		orderDate: "02 Jan | 11:29am",
		status: "Pending",
	},
	{
		id: 7545,
		img: images.product5,
		itemName: "Two piars of shoes",
		amount: 897,
		quantity: 3,
		orderDate: "02 Jan | 11:29am",
		status: "Paid",
	},
	{
		id: 8545,
		img: images.product4,
		itemName: "Two piars of shoes",
		amount: 897,
		quantity: 6,
		orderDate: "02 Jan | 11:29am",
		status: "Pending",
	},
	{
		id: 9545,
		img: images.product2,
		itemName: "Two piars of shoes",
		amount: 897,
		quantity: 4,
		orderDate: "02 Jan | 11:29am",
		status: "Pending",
	},
];
